// <auto-generated />
namespace ASP_Reboot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addwarningandrefilllevelstoinventory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addwarningandrefilllevelstoinventory));
        
        string IMigrationMetadata.Id
        {
            get { return "201606010009581_add warning and refill levels to inventory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
